name: CD

on:
  push:
    branches:
    - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build the résumé
      uses: xu-cheng/latex-action@v2
      with:
        latexmk_use_xelatex: true
        args: -jobname=resume
        root_file: main.tex

    - name: Build the cover letter
      uses: xu-cheng/latex-action@v2
      with:
        latexmk_use_xelatex: true
        args: -jobname=cover
        root_file: main.tex

    - name: Collect deployment files
      run: |
        cp public/index.html resume/
        cp resume.pdf resume/
        cp cover.pdf resume/

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./resume
        force_orphan: true
